# Generated by Django 4.1 on 2023-02-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_auto_20230213_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
